# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AudioTest_config = debug
  GFXTest_config = debug
endif
ifeq ($(config),release)
  AudioTest_config = release
  GFXTest_config = release
endif

PROJECTS := AudioTest GFXTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AudioTest:
ifneq (,$(AudioTest_config))
	@echo "==== Building AudioTest ($(AudioTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f AudioTest.make config=$(AudioTest_config)
endif

GFXTest:
ifneq (,$(GFXTest_config))
	@echo "==== Building GFXTest ($(GFXTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f GFXTest.make config=$(GFXTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f AudioTest.make clean
	@${MAKE} --no-print-directory -C . -f GFXTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AudioTest"
	@echo "   GFXTest"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"